global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'watcher'
    metrics_path: /metrics
    static_configs:
      - targets: ['watcher:5000']

  - job_name: 'archivebox'
    static_configs:
      - targets: ['archivebox:8000']
